export enum ROUTES {
  DASHBOARD = "/account/dashboard",
  CLIENTS = "/account/clients",
  PROJECTS = "/account/projects",
  BILLING = "/account/billing",
  ACTIVITIES = "/account/activities",
  TEAM_MANAGEMENT = "/account/team-management",
  ANALYTICS = "/account/analytics",
  TASKS = "/account/tasks",
  CONVERSATIONS = "/account/conversations",
  CONVERSATION = "/account/conversations/:id",
  SUPPORT = "/account/support",
  RESOURCE_CONVERSATIONS = "/resources/conversations",
  RESOURCE_CONVERSATION = "/resources/conversations/:id",
  LOGOUT = "/logout",
  REGISTER = "/auth/register",
  LOGIN = "/auth/login",
  GOOGLE_AUTH = "/auth/google-auth",
  GOOGLE_AUTH_CB = "/auth/google-auth/callback",
  FORGOT_PASSWORD = "/auth/forgot-password",
  RESET_PASSWORD = "/auth/reset-password/:token",
  "2FA" = "/auth/2fa",
  SEND_VERIFICATION = "/auth/send-verification",
  VERIFY_ACCOUNT = "/auth/verify/:id",
}
